"""add_exam_tables

Revision ID: 18a9377a14f9
Revises: 48a8fa697564
Create Date: 2026-02-19 11:58:47.002652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a9377a14f9'
down_revision = '48a8fa697564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('title', sa.String(length=200), nullable=False, comment='시험 제목'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_questions',
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False, comment='문제 번호 (1~30)'),
    sa.Column('question_type', sa.Enum('multiple_choice', 'short_answer', name='questiontype'), nullable=False, comment='문제 유형'),
    sa.Column('correct_answer', sa.String(length=500), nullable=False, comment='정답'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_submissions',
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['student_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_answers',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['exam_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_answers')
    op.drop_table('exam_submissions')
    op.drop_table('exam_questions')
    op.drop_table('exams')
    # ### end Alembic commands ###
