"""Add instructor time records and hourly rate

Revision ID: fae5c7a048a3
Revises: 50bdd01d3697
Create Date: 2026-02-20 21:02:17.024728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae5c7a048a3'
down_revision = '50bdd01d3697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_time_records',
    sa.Column('instructor_id', sa.String(), nullable=False, comment='조교 ID'),
    sa.Column('work_date', sa.Date(), nullable=False, comment='근무 날짜'),
    sa.Column('clock_in', sa.Time(), nullable=True, comment='출근 시간'),
    sa.Column('clock_out', sa.Time(), nullable=True, comment='퇴근 시간'),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True, comment='근무 시간 (시간 단위)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instructor_id', 'work_date', name='uix_instructor_work_date')
    )
    op.create_index(op.f('ix_instructor_time_records_instructor_id'), 'instructor_time_records', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_time_records_work_date'), 'instructor_time_records', ['work_date'], unique=False)
    op.add_column('instructors', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='시급'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'hourly_rate')
    op.drop_index(op.f('ix_instructor_time_records_work_date'), table_name='instructor_time_records')
    op.drop_index(op.f('ix_instructor_time_records_instructor_id'), table_name='instructor_time_records')
    op.drop_table('instructor_time_records')
    # ### end Alembic commands ###
