"""Clean migration for new schema

Revision ID: f6f22d481236
Revises: 
Create Date: 2026-02-15 20:08:31.833307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f22d481236'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_schedules',
    sa.Column('name', sa.String(), nullable=False, comment='수업명 (예: 수학 정규반)'),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='요일 (0=월요일, 6=일요일)'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='수업 시작 시간'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='수업 종료 시간'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('description', sa.String(), nullable=True, comment='수업 설명'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='instructorstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_email'), 'instructors', ['email'], unique=True)
    op.create_table('students',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', name='studentstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('study_sessions',
    sa.Column('name', sa.String(), nullable=False, comment='자습 시간 이름 (예: 야간 자습)'),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='요일 (0=월요일, 6=일요일)'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='자습 시작 시간'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='자습 종료 시간'),
    sa.Column('max_instructors', sa.Integer(), nullable=True, comment='필요한 조교 수'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('description', sa.String(), nullable=True, comment='자습 시간 설명'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('student_id', sa.String(), nullable=False, comment='학생 ID'),
    sa.Column('class_schedule_id', sa.String(), nullable=False, comment='수업 시간표 ID'),
    sa.Column('attendance_date', sa.Date(), nullable=False, comment='출석 날짜'),
    sa.Column('attended', sa.Boolean(), nullable=False, comment='출석 여부'),
    sa.Column('attendance_time', sa.DateTime(), nullable=True, comment='출석 체크 시간'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_schedule_id'], ['class_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_schedule_id', 'attendance_date', name='unique_student_class_date_attendance')
    )
    op.create_table('grades',
    sa.Column('student_id', sa.String(), nullable=False, comment='학생 ID'),
    sa.Column('exam_date', sa.Date(), nullable=False, comment='시험 날짜'),
    sa.Column('exam_type', sa.String(length=50), nullable=False, comment='시험 유형 (예: 중간고사, 기말고사, 모의고사)'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='과목 (기본: 수학)'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False, comment='획득 점수'),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='만점'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_exam', 'grades', ['student_id', 'exam_date'], unique=False)
    op.create_table('instructor_assignments',
    sa.Column('study_session_id', sa.String(), nullable=False, comment='자습 시간 ID'),
    sa.Column('instructor_id', sa.String(), nullable=False, comment='조교 ID'),
    sa.Column('assignment_date', sa.Date(), nullable=False, comment='배치 날짜'),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True, comment='배치 확정 여부'),
    sa.Column('notes', sa.String(), nullable=True, comment='특이사항'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructor_assignments')
    op.drop_index('idx_student_exam', table_name='grades')
    op.drop_table('grades')
    op.drop_table('attendance')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_instructors_email'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_table('class_schedules')
    # ### end Alembic commands ###
