"""Add account_number to instructors

Revision ID: b10d0512df01
Revises: 18a9377a14f9
Create Date: 2026-02-20 20:31:33.154117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d0512df01'
down_revision = '18a9377a14f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('account_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'account_number')
    # ### end Alembic commands ###
