"""Add bank_name to instructors

Revision ID: 50bdd01d3697
Revises: b10d0512df01
Create Date: 2026-02-20 20:32:17.108643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bdd01d3697'
down_revision = 'b10d0512df01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('bank_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'bank_name')
    # ### end Alembic commands ###
